name: Hyvor workflow
on:
  workflow_dispatch:
jobs:
  makefiles:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Getting
      uses: fjogeleit/http-request-action@master
      id: myRequest
      with:
        url: 'https://talk.hyvor.com/api/data/v1/pages?website_id=${{ secrets.HYVOR_WEBSITEID }}&api_key=${{ secrets.HYVOR_APIKEY }}&limit=10&sort=reactions_count'
        method: 'GET'
    - name: Create A File
      uses: 1arp/create-a-file-action@0.2
      with:
        path: '_data'
        file: 'reactions.json'
        content: ${{steps.myRequest.outputs.response}}
    - name: final commit
      uses: zwaldowski/git-commit-action@v1
      id: git_commit
    - name: show
      run: echo "${{ steps.git_commit.outputs.sha }}"
