name: Hyvor workflow
on:
  workflow_dispatch:
jobs:
  makefiles:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Getting
      uses: fjogeleit/http-request-action@master
      id: myRequest
      with:
        url: 'https://talk.hyvor.com/api/data/v1/pages'
        method: 'POST'
        website_id: ${{ secrets.HYVOR_WEBSITEID }}
        api_key: ${{ secrets.HYVOR_APIKEY }}
        sort: ''
    - name: Show File
      run: echo ${{ steps.myRequest.outputs.response }}
