name: 'IndexNow'
on:
  workflow_dispatch:
jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v3
        with:
          sitemap-location: 'https://www.6x8.org/sitemap.xml'
          key: ${{ secrets.INDEXNOW_KEY }}
